config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get "rilegature", to: "pages#rilegature"
  get "copertine", to: "pages#copertine"
  get "formati", to: "pages#formati"
  get "gallery", to: "pages#gallery"


  get "step1", to: "pages#step1"
  get "step2", to: "pages#step2"
  get "step3", to: "pages#step3"
  get "step4", to: "pages#step4"
  get "confirmation", to: "pages#confirmation"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def rilegature
  end

  def copertine
  end

  def formati
  end

  def gallery
  end

  def step1
  end

  def step2
  end

  def step3
  end

  def step4
  end

  def confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title Stampatesi
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container.col-md-8.col-md-offset-2
      = link_to root_path do
        h1 Stampa Tesi
    .container.col-md-8.col-md-offset-2 style='min-height:500px;'
      = yield

    .footer
      .col-md-6
        h3 COMPANY NAME
        p
          | 2232 Address
          br
          | Suburb
          br
          | Sydney NSW
      .col-md-3
        h3 Foto Gallery
        br
        | something should go here
      .col-md-3
        h3 FOOOOO
        br
        | Lorem ipsum ..

app/views/pages/confirmation.html.slim
h1 Conferma ordine #123213213.


p bla bla bla bal bald d


p foooooooooo



p grazie,
p Team

app/views/pages/copertine.html.slim
h1 copertine

app/views/pages/formati.html.slim
h1 Formati

app/views/pages/gallery.html.slim
h1 Photo Gallery

app/views/pages/index.html.slim
.row.steps
  .step.col-md-3
    = link_to step1_path do
      .round 1
      .content
        i.fa.fa-book
        p Seleziona Modello
  .step.col-md-3
    = link_to step2_path do
      .round 2
      .content
        i.fa.fa-file-pdf-o
        p Verifica PDF
  .step.col-md-3
    = link_to step3_path do
      .round 3
      .content
        i.fa.fa-upload
        p Upload File
  .step.col-md-3
    = link_to step4_path do
      .round 4
      .content
        i.fa.fa-shopping-cart
        p
          | Ricevi a Casa
          br
          | Ritira in negozio

.row.rett-container
  .col-md-6.rett-ext
    = link_to rilegature_path do
      .rettangolo
        | Rilegature
  .col-md-6.rett-ext
    = link_to copertine_path do
      .rettangolo
        | Copertine
  .col-md-6.rett-ext
    .rettangolo
      = link_to formati_path do
        | Formati
  .col-md-6.rett-ext
    .rettangolo
      = link_to gallery_path do
        | Tipologia Carta

app/views/pages/rilegature.html.slim
h1 Rilegature

app/views/pages/step1.html.slim
.container
  h2 Seleziona modello



p Form selezione


p totale

p quantita'

p spedizione

p totale ordine

p data consegna prevista



= link_to step2_path, class:'btn btn-default' do
  | VERIFICA PDF

app/views/pages/step2.html.slim
h2 Verifica pdf

p download template
p download foglio con margini
p relativi al formato/libro scelto


h4 Checklist da confermare:

p dimensione foglio

p qualita' foto

p dpi

p magini

p max MB File

= link_to step1_path, class:'btn btn-default' do
  | BACK

= link_to step3_path, class:'btn btn-default' do
  | UPLOAD FILES

app/views/pages/step3.html.slim
h2 Upload file


p 1 o 2 file dipende da tipologia scelta




= link_to step2_path, class:'btn btn-default' do
  | BACK

= link_to step4_path, class:'btn btn-default' do
  | FINALIZZA

app/views/pages/step4.html.slim
h2 Completamento ordine


p login/registrazione

p spedizione o selezione negozio

p pagamento



= link_to step3_path, class:'btn btn-default' do
  | BACK

= link_to confirmation_path, class:'btn btn-default' do
  | CONFERMA ORDINE